### ISSUE TITLE
Doesn't actually work with Tagbar

### ISSUE THREAD

**Issue by tandrewnichols** [okcompute/esctags#4]
The readme suggests this can be used for Tagbar. I'm setting es-ctags as the ctags bin for Tagbar like this:

```
let g:tagbar_ctags_bin = 'es-ctags'
```

and I get this when I toggle tagbar:

<img width="1125" alt="screen shot" src="https://user-images.githubusercontent.com/2755760/36993853-467a108e-207d-11e8-94e7-6c2628b1e750.png">

Seems to not like that there's no `--version` flag.

**Comment by tandrewnichols** [comment]
I manually added a version flag to the binary and that got it a little farther, but I still get an error:

<img width="1133" alt="screen shot 1" src="https://user-images.githubusercontent.com/2755760/36994045-e12b4a76-207d-11e8-9d77-1f54e50cfe08.png">

Basically, Tagbar wants to run `<binary> --version` and get back something matching `'\(Exuberant\|Universal\) Ctags'` with a version greater than 5.5 before it will try to run the binary with a file name.

**Comment by tandrewnichols** [comment]
Actually, fwiw, jsctags doesn't work with Tagbar for the same reason.

**Comment by okcompute** [comment]
HI, 

I don't use and maintain this package anymore (I added a note in the readme). I'm now using *Unversal Ctags* (https://ctags.io) which works fine for my needs.

Regards,

Pascal

**Comment by tandrewnichols** [comment]
Ok, thanks for the info.
